export const ORDERS = [
  {
    productId: 1,
    productName: "Asus VivoBook 15- QHD 240Hz RTX 3070 i5 quadcore",
    paymentCycleDone: 2,
    paymentCycleTotal: 3,
    nextDue: "1660102588000",
    monthlyRental: 902,
    insurance: 100,
    gst: 18,
    productQuantity: 1,
    startDate: "1659918056000",
    endDate: "1667792188000",
  },
  {
    productId: 2,
    productName: "Dell Inspiron 15- QHD 240Hz RTX 3070 i5 quadcore",
    paymentCycleDone: 3,
    paymentCycleTotal: 6,
    nextDue: "1661818856000",
    monthlyRental: 9020,
    insurance: 100,
    gst: 18,
    productQuantity: 1,
    startDate: "1656560188000",
    endDate: "1672457788000",
  },
];

export const TEXT = {
  checkoutSummaryTitle: "Order Summary",
  checkoutSummaryMonthly: "Monthly Rental",
  checkoutSummaryInsurance: "Insurance",
  checkoutSummaryGST: "GST - 18%",
  checkoutSummaryTotal: "Total Amount",
  checkoutSummaryPaying: "paying for 1 month",
  checkoutSummaryKYC: "Documents for KYC and Verification will be asked",
  checkoutCardInstallment1: "Paying your",
  checkoutCardInstallment2: "installment",
  checkoutCardCycle: "Payment Cycle",
  cardSubtitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  cardMobileTitle: "Enter Mobile Number to login",
  cardEmailTitle: "Enter Name & Email Id",
  cardNoOrderTitle: "You have not placed any order with us.",
  cardNoOrderSubtitle1: "Reach out to",
  cardNoOrderSubtitle2: "to check our inventory",
  cardNoOrderMobile: "+91-987654321",
  cardOrders: "Your Orders",
  cardOtpTitle: "Hello!",
  cardOtpsubText: "Please enter the OTP sent to",
  cardOtpNotReceived: "I haven't recieved a code",
  orderCardPaymentCycle: "Payment Cycle",
  orderCardNextDue: "Next Due on",
  orderCardPerMonth: "per month",
  orderCardRentalPeriod: "Rental Period",
  orderCardQty: "Qty.",
  orderCardPrice: "Price",
  orderCardBillingDate: "Billing Date",
  orderCardEndDate: "End Date",
  orderCardStartDate: "Start Date",
  orderCardGST: "GST",
  orderCardInsurance: "Insurance",
  orderCardMonthly: "Monthly Rental",
  onboardSubContent:
    "If you are part of our beta version,click below to start your journey",
  onboardMainContent: "Get tech when you want, As long as you want",
  onboardBottomText1: "Are you a Freelancer? Startup? Gamer?",
  onboardBottomText2: "We have something for all your requirements",
  wrongOtp: "The OTP entered is wrong. Please try again",
};

export const MONTH = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
