export const ORDERS = [
  {
    productId: 1,
    productName: "Asus VivoBook 15- QHD 240Hz RTX 3070 i5 quadcore",
    paymentCycleDone: 2,
    paymentCycleTotal: 3,
    nextDue: "1660102588000",
    monthlyRental: 902,
    insurance: 100,
    gst: 18,
    productQuantity: 1,
    startDate: "1659918056000",
    endDate: "1667792188000",
  },
  {
    productId: 2,
    productName: "Dell Inspiron 15- QHD 240Hz RTX 3070 i5 quadcore",
    paymentCycleDone: 3,
    paymentCycleTotal: 6,
    nextDue: "1661818856000",
    monthlyRental: 9020,
    insurance: 100,
    gst: 18,
    productQuantity: 1,
    startDate: "1656560188000",
    endDate: "1672457788000",
  },
  {
    productId: 3,
    productName: "Dell Inspiron 15- QHD 240Hz RTX 3070 i5 quadcore",
    paymentCycleDone: 1,
    paymentCycleTotal: 3,
    nextDue: "1662077149000",
    monthlyRental: 9020,
    insurance: 100,
    gst: 18,
    productQuantity: 1,
    startDate: "1656560188000",
    endDate: "1672457788000",
  },
  {
    productId: 4,
    productName: "Dell Inspiron 15- QHD 240Hz RTX 3070 i5 quadcore",
    paymentCycleDone: 0,
    paymentCycleTotal: 6,
    nextDue: "1661818856000",
    monthlyRental: 9020,
    insurance: 100,
    gst: 18,
    productQuantity: 1,
    startDate: "1656560188000",
    endDate: "1672457788000",
  },
];

export const ADDRESS_INFO = [
  {
    addressId: 1,
    address:
      "134, apz apartments, near tech park, Bellandur Cross, Electronic City Phase 1, Bengaluru Urban, Bengaluru, Karnataka - 560094",
  },
  {
    addressId: 2,
    address:
      "134, apz apartments, near tech park, Bellandur Cross, Electronic City Phase 1, Bengaluru Urban, Bengaluru, Karnataka - 560094",
  },
  {
    addressId: 3,
    address:
      "134, apz apartments, near tech park, Bellandur Cross, Electronic City Phase 1, Bengaluru Urban, Bengaluru, Karnataka - 560094",
  },
];

export const CHOOSE_TYPE = {
  1: "student",
  2: "workingProfessional",
  3: "partnershipFirm",
  4: "pvtLlpPublic",
};

export const TEXT = {
  checkoutSummaryTitle: "Order Summary",
  checkoutSummaryMonthly: "Monthly Rental",
  checkoutSummaryInsurance: "Insurance",
  checkoutSummaryGST: "GST - 18%",
  checkoutSummaryTotal: "Total Amount",
  checkoutSummaryPaying: "paying for 1 month",
  checkoutSummaryKYC: "Documents for KYC and Verification will be asked",
  checkoutCardInstallment1: "Paying your",
  checkoutCardInstallment2: "installment",
  checkoutCardCycle: "Payment Cycle",
  checkoutAddressTitle: "Choose Address",
  chooseTypeTitle: "Lets get you verified",
  chooseTypeSubtitle: "Choose which suits you best",
  cardSubtitle: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  cardMobileTitle: "Enter Mobile Number to login",
  cardEmailTitle: "Enter Name & Email Id",
  cardNoOrderTitle: "You have not placed any order with us.",
  cardNoOrderSubtitle1: "Reach out to",
  cardNoOrderSubtitle2: "to check our inventory",
  cardNoOrderMobile: "+91-987654321",
  cardOrders: "Your Orders",
  cardOtpTitle: "Hello!",
  cardOtpsubText: "Please enter the OTP sent to",
  cardOtpNotReceived: "I haven't recieved a code",
  orderCardPaymentCycle: "Payment Cycle",
  orderCardNextDue: "Next Due on",
  orderCardPerMonth: "per month",
  orderCardRentalPeriod: "Rental Period",
  orderCardQty: "Qty.",
  orderCardPrice: "Price",
  orderCardBillingDate: "Billing Date",
  orderCardEndDate: "End Date",
  orderCardStartDate: "Start Date",
  orderCardGST: "GST",
  orderCardInsurance: "Insurance",
  orderCardMonthly: "Monthly Rental",
  onboardSubContent:
    "If you are part of our beta version,click below to start your journey",
  onboardMainContent: "Get tech when you want, As long as you want",
  onboardBottomText1: "Are you a Freelancer? Startup? Gamer?",
  onboardBottomText2: "We have something for all your requirements",
  verificationCardTitle: "Verification",
  verificationCardPan: "Enter PAN details",
  verificationCardSelfie: "Take a Selfie",
  verificationCardBank: "Enter Bank details",
  verificationCardFooter1: "One step closer to equipp",
  verificationCardFooter2: "Check your email for a confirmation",
  verificationCardFooter3:
    "A team member will reach out to you for additional info.",
  verificationCardProfession: "Choose Profession",
  verificationCardPanGST: "Enter Co. PAN and GST Details",
  verificationCardCoBank: "Enter Co. Bank details",
  verificationCardDIN: "Enter DIN Details",
  panDetailsTitle: "Enter PAN & Mobile Number",
  panDetailsSubtitle: "Don't have a PAN Card? Upload Guardian Details",
  panDetailsFileText: "Files have to be in .PDF/ jpeg/ png format",
  panDetailsFileInput: "Choose from Files",
  bankStatementTitle: "Upload your Bank Statement",
  bankStatementSubtitle: "Please upload 6 months bank statement from",
  bankStatementPwdProtected: "Is it password protected?",
  bankStatementFileText: "Files have to be in .PDF format only",
  bankStatementTerms: "I accept all Terms and Conditions",
  verifyBankTitle: "Verify document password",
  selfieTitle: "Take a Selfie",
  selfieSubtext:
    "Make sure we can see your full face clearly no hats, glasses or anything that obstructs your face",
  wrongOtp: "The OTP entered is wrong. Please try again",
  wrongInput: "Wrong input, please enter again",
  professionTitle: "Choose type",
  professionSubtitle: "of profession",
  workEmailTitle: "Work Email",
  coPanGstTitle: "Enter Company PAN & GST",
  partnerPanTitle: "Enter Partner",
  partnerPanSubtitle: "PAN & Mobile Number",
  partnerPanSubText: "Enter one of the Partners Details",
  directorDinTitle: "Enter Director's DIN",
  noPageTitle: "Error 404, page not found.",
};

export const MONTH = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
